title: Alexandru Militaru
description: First year graduate CS student student. Passionate about operating systems & compilers. Interested in research & development. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
