title: Alexandru Militaru
description: "First year MSc student.
             Passionate about operating systems and compilers.
             Interested in research and innovation."
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
